### ISSUE TITLE
你好。python3.6，版本的，训练，一直不收敛，loss 0.7左右，acc 0.7左右

### ISSUE THREAD

**Issue by shaoshuaiche** [whai362/PSENet#118]

**Comment by Shualite** [comment]
请问您训练时候的pytorch版本，为啥我直接运行train_ic15.py dataloader会出异常

**Comment by Shualite** [comment]
您是运行的train_ctw1500.py吗？

**Comment by Shualite** [comment]
`Traceback (most recent call last):
  File "train_ic15.py", line 283, in <module>
    main(args)
  File "train_ic15.py", line 251, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "train_ic15.py", line 112, in train
    for batch_idx, (imgs, gt_texts, gt_kernels, training_masks) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)`
我遇见的问题如上。

**Comment by Lanme** [comment]
检测得到文字么？

**Comment by superblackwoo** [comment]
我也有问题如下：
Traceback (most recent call last):
  File "G:/aProject_CV/PSENet-master/PSENet-master/train_ic15.py", line 283, in <module>
    main(args)
  File "G:/aProject_CV/PSENet-master/PSENet-master/train_ic15.py", line 251, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "G:/aProject_CV/PSENet-master/PSENet-master/train_ic15.py", line 112, in train
    for batch_idx, (imgs, gt_texts, gt_kernels, training_masks) in enumerate(train_loader):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by zgsxwsdxg** [comment]
> No description provided.



> 请问您训练时候的pytorch版本，为啥我直接运行train_ic15.py dataloader会出异常

兄弟，你好！python3.6 pse c++ 模块，需要修改那些？我的改了make时，老是报错 error"include/pybind11/detail/common.h:112:10: fatal error: python3.6m/Python.h: No such file or directory" 
谢谢！

**Comment by RoseSakurai** [comment]
python3版本已经发布，如果大家感兴趣请关注！
