### ISSUE TITLE
TypeError: function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by Shualite** [whai362/PSENet#119]
when i ran python train_ic15.py, i got this:
```
Traceback (most recent call last):
  File "train_ic15.py", line 283, in <module>
    main(args)
  File "train_ic15.py", line 251, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "train_ic15.py", line 112, in train
    for batch_idx, (imgs, gt_texts, gt_kernels, training_masks) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: function takes exactly 5 arguments (1 given)
```

**Comment by Shualite** [comment]
@whai362 The Version of pytorch is 0.4.1, by the way, pytorch 1.0.0 also have this problem

**Comment by Shualite** [comment]
I' m OK! When I change python2.7 instead of 3.6 , This problem is over!
