### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by jun214384468** [whai362/PSENet#132]
Traceback (most recent call last):
  File "/home/yan/disk/All_python_Text/PSENet-master/test_ic15.py", line 220, in <module>
    test(args)
  File "/home/yan/disk/All_python_Text/PSENet-master/test_ic15.py", line 154, in test
    pred = pse(kernels, args.min_kernel_area / (args.scale * args.scale))
  File "/home/yan/disk/All_python_Text/PSENet-master/pse/__init__.py", line 14, in pse
    ret = np.array(cpse(polys, min_area), dtype='int32')
TypeError: 'module' object is not callable

我在测试的时候就出现这个问题了,能帮帮我吗?

**Comment by jun214384468** [comment]
python version pse的实现代码可以给我一下吗?

**Comment by fxwfzsxyq** [comment]
pypse.py 这个不就是python版的吗

**Comment by jun214384468** [comment]
> pypse.py 这个不就是python版的吗

是的  我那会没找到 现在已经会拉  谢谢啦
