### ISSUE TITLE
ERRROR: PyUnicodeUCS2_AsUTF8String

### ISSUE THREAD

**Issue by AliceWunana** [whai362/PSENet#35]
除了重新编译python，不知有没有其他解决方法？
Traceback (most recent call last):
  File "*/PSENet/test_ic15.py", line 19, in <module>
    from pse import pse
  File "*/PSENet/pse/__init__.py", line 11, in <module>
    from .adaptor import pse as cpse
ImportError: */PSENet/pse/adaptor.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
environment:
conda 
Python 2.7.13

**Comment by jun214384468** [comment]
> 除了重新编译python，不知有没有其他解决方法？
> Traceback (most recent call last):
> File "_/PSENet/test_ic15.py", line 19, in from pse import pse File "_/PSENet/pse/**init**.py", line 11, in
> from .adaptor import pse as cpse
> ImportError: */PSENet/pse/adaptor.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
> environment:
> conda
> Python 2.7.13

请问你ide问题解决了吗?我也出现了
