### ISSUE TITLE
python3.6运行train_ic15.py 出错

### ISSUE THREAD

**Issue by QQ1696311291** [whai362/PSENet#55]
checkpoint path: checkpoints/ic15_resnet50_bs_2_ep_600
init lr: 0.00100000
('schedule: ', [200, 400])
Training from scratch.

Epoch: [1 | 600] LR: 0.001000
Traceback (most recent call last):
  File "train_ic15.py", line 289, in <module>
    main(args)
  File "train_ic15.py", line 257, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "train_ic15.py", line 175, in train
    return (losses.avg, score_text['Mean Acc'], score_kernel['Mean Acc'], IC15Loaderscore_text['Mean IoU'], score_kernel['Mean IoU'])
UnboundLocalError: local variable 'score_text' referenced before assignment
求帮助

**Comment by sonack** [comment]
@QQ1696311291  你的数据应该没放对位置

**Comment by QQ1696311291** [comment]
> @QQ1696311291 你的数据应该没放对位置

您好，能加个联系方式咨询这个问题吗？或者私信下也行

**Comment by QQ1696311291** [comment]
能加个联系方式，详细谈谈这个问题吗？

**Comment by Tian14267** [comment]
我遇到了 out of memory的问题，我的显卡1080Ti。请问你遇到了吗？怎么解决啊
@QQ1696311291 @sonack 
checkpoint path: checkpoints/ic15_resnet50_bs_16_ep_600
init lr: 0.00100000
('schedule: ', [200, 400])
Training from scratch.

Epoch: [1 | 600] LR: 0.001000
Traceback (most recent call last):
  File "train_ic15.py", line 283, in <module>
    main(args)
  File "train_ic15.py", line 251, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "train_ic15.py", line 120, in train
    outputs = model(imgs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hj/smbshare/fffan/PSEnet/Pytorch_PSENet-master/models/fpn_resnet.py", line 199, in forward
    h = self.layer4(h)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hj/smbshare/fffan/PSEnet/Pytorch_PSENet-master/models/fpn_resnet.py", line 79, in forward
    out = self.bn1(out)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 10.91 GiB total capacity; 10.26 GiB already allocated; 49.44 MiB free; 7.67 MiB cached)

**Comment by jiangzz1628** [comment]
@QQ1696311291 解决了吗？我也出现了这个问题。

**Comment by shaoshuaiche** [comment]
你好。训练结果正常吗

**Comment by shaoshuaiche** [comment]
python3.6，版本的，训练，一直不收敛，loss 0.7左右，acc 0.7左右

**Comment by apple2333cream** [comment]
python3 和python2的区别， 整除运算符，py2是/ ，Python3是//

**Comment by VixeruntR** [comment]
> 
> 
> python3 和python2的区别， 整除运算符，py2是/ ，Python3是//

我也遇到了这个问题 请问修改哪里呢  代码里每个/都要修改成//吗？
