### ISSUE TITLE
 CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)

### ISSUE THREAD

**Issue by Tian14267** [whai362/PSENet#65]
你好，我运行你的 "train_ctw1500.py" ，结果报“CUDA error: out of memory”的错误。我的GPU是1080Ti，batch_size = 4, img_size = 160.请问你知道什么原因吗？

I run your "train_ctw1500.py" code, and get this error:

Epoch: [1 | 100] LR: 0.001000
Traceback (most recent call last):
  File "train_ctw1500.py", line 283, in <module>
    main(args)
  File "train_ctw1500.py", line 251, in main
    train_loss, train_te_acc, train_ke_acc, train_te_iou, train_ke_iou = train(train_loader, model, dice_loss, optimizer, epoch)
  File "train_ctw1500.py", line 120, in train
    outputs = model(imgs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 159, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)
My gpu is 1080Ti，and I decrease the batch_size to 4,and img_size = 160.Do you know how to solve this problem?

**Comment by ganliqiang** [comment]
decrease the batch_size
