### ISSUE TITLE
a problem about pse ImportError: libopencv_cudabgsegm.so.3.4:

### ISSUE THREAD

**Issue by fujingling** [whai362/PSENet#76]
from .adaptor import pse as cpse
ImportError: libopencv_cudabgsegm.so.3.4: cannot open shared object file: No such file or directory

**Comment by luckydog5** [comment]
Have solved it , i met the same error.

**Comment by luckydog5** [comment]
First:    ldd adaptor.so

linux-vdso.so.1 =>  (0x00007fffdbdd8000)
	libopencv_shape.so.3.4 => not found
	libopencv_videostab.so.3.4 => not found
	libopencv_photo.so.3.4 => not found
	libopencv_superres.so.3.4 => not found
	libopencv_objdetect.so.3.4 => not found
	libopencv_dnn.so.3.4 => not found
	libopencv_stitching.so.3.4 => not found
	libopencv_calib3d.so.3.4 => not found
	libopencv_video.so.3.4 => not found
	libopencv_ml.so.3.4 => not found
	libopencv_features2d.so.3.4 => not found
	libopencv_highgui.so.3.4 => not found
	libopencv_videoio.so.3.4 => not found
	libopencv_imgcodecs.so.3.4 => not found
	libopencv_imgproc.so.3.4 => not found
	libopencv_flann.so.3.4 => not found
	libopencv_core.so.3.4 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6b4d3c2000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6b4d0c0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6b4ceaa000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6b4cae6000)
	/lib64/ld-linux-x86-64.so.2 (0x0000564a795de000)

Then do:  sudo ln -s /usr/local/lib64/libopencv_dnn.so.3.4 libopencv_dnn.so.3.4 
one by one .

**Comment by lixiangpengcs** [comment]
> First: ldd adaptor.so
> 
> linux-vdso.so.1 => (0x00007fffdbdd8000)
> libopencv_shape.so.3.4 => not found
> libopencv_videostab.so.3.4 => not found
> libopencv_photo.so.3.4 => not found
> libopencv_superres.so.3.4 => not found
> libopencv_objdetect.so.3.4 => not found
> libopencv_dnn.so.3.4 => not found
> libopencv_stitching.so.3.4 => not found
> libopencv_calib3d.so.3.4 => not found
> libopencv_video.so.3.4 => not found
> libopencv_ml.so.3.4 => not found
> libopencv_features2d.so.3.4 => not found
> libopencv_highgui.so.3.4 => not found
> libopencv_videoio.so.3.4 => not found
> libopencv_imgcodecs.so.3.4 => not found
> libopencv_imgproc.so.3.4 => not found
> libopencv_flann.so.3.4 => not found
> libopencv_core.so.3.4 => not found
> libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6b4d3c2000)
> libm.so.6 => /lib64/libm.so.6 (0x00007f6b4d0c0000)
> libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6b4ceaa000)
> libc.so.6 => /lib64/libc.so.6 (0x00007f6b4cae6000)
> /lib64/ld-linux-x86-64.so.2 (0x0000564a795de000)
> 
> Then do: sudo ln -s /usr/local/lib64/libopencv_dnn.so.3.4 libopencv_dnn.so.3.4
> one by one .
I met the same error and I construct link as you suggest. But the error is still alive:
Traceback (most recent call last):
  File "test_ic15.py", line 19, in <module>
    from pse import pse
  File "/home/lixiangpeng/workspace/textDetection/PSENet/pse/__init__.py", line 11, in <module>
    from .adaptor import pse as cpse
ImportError: libopencv_imgproc.so.3.4: cannot open shared object file: No such file or directory

when I run:  ldd adaptor.so
        linux-vdso.so.1 =>  (0x00007ffcf4fe8000)
	libopencv_imgproc.so.3.4 (0x00007fe7822d4000)
	libopencv_core.so.3.4 (0x00007fe780f79000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe780bf7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe7808ee000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe7806d8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe78030e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe7800f1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe77feed000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe77fce5000)
	libz.so.1 => /home/lixiangpeng/env/anaconda3/envs/psenet/lib/libz.so.1 (0x00007fe77facd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe785383000)
Can you teel me that how you solve your problem?

**Comment by saicoco** [comment]
opencv 4 can solve it

**Comment by luckydog5** [comment]
How you install opencv3.4, it sames that you don't have libopencv_imgproc.so.3.4 installed.

**Comment by fujingling** [comment]
thank you very much for@luckydog5  @saicoco
I manually compiled opencv3.4，but didn't configure  environment library correctly, so I met this error，I solved the problem by:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/export/usr/opencv3.4/lib64`
