### ISSUE TITLE
有没有遇到这个问题的呀 ImportError: /opt/data/private/PSENet/pse/adaptor.so: undefined symbol: _ZN2cv8fastFreeEPv

### ISSUE THREAD

**Issue by hetianduan** [whai362/PSENet#97]
make: Leaving directory '/opt/data/private/PSENet/pse'
Traceback (most recent call last):
  File "test_ic15.py", line 19, in <module>
    from pse import pse
  File "/opt/data/private/PSENet/pse/__init__.py", line 11, in <module>
    from .adaptor import pse as cpse
ImportError: /opt/data/private/PSENet/pse/adaptor.so: undefined symbol: _ZN2cv8fastFreeEPv

**Comment by JiaquanYe** [comment]
I have met this situation, too

**Comment by jiangzz1628** [comment]
解决了吗

**Comment by hetianduan** [comment]
> 解决了

> 解决了吗
编译安装Opencv

**Comment by hetianduan** [comment]
> 解决了吗
编译安装opencv

**Comment by jun214384468** [comment]
> > 解决了吗
> > 编译安装opencv

你好,我安装了opencv3.4.2
但是还是报这个错,主要是在python中 pse/__init__.py中这一句代码就有红线提示from .adaptor import pse as cpse

**Comment by Magic-OO** [comment]
请问有人解决了这个问题了吗？求解答啊

**Comment by waxz** [comment]
https://stackoverflow.com/questions/51308292/swig-linker-undefined-symbol-zn2cv8fastfreeepv-cvfastfreevoid
You have to pass libraries and library-paths to the build-process by using arguments libraries and library_dirs
```py
ext = Extension(....
                libraries=["opencv_xfeatures2d", "opencv_features2d", 
                           "opencv_highgui", "opencv_core"],
                library_dirs=['/usr/local/lib']
                )
```

**Comment by buptlihang** [comment]
You may not get all the information related to the compilation of opencv, try to run
apt-get install pkg-config
